// componentes-v0/components/initial-capital-modal.tsx
"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { X, DollarSign } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface InitialCapitalModalProps {
  onClose: () => void
  onSave: (value: number) => void
}

export default function InitialCapitalModal({ onClose, onSave }: InitialCapitalModalProps) {
  const [value, setValue] = useState("")

  const handleSave = () => {
    const numValue = Number.parseFloat(value) || 0
    onSave(numValue)
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50"
    >
      <motion.div
        initial={{ scale: 0.9, y: 20 }}
        animate={{ scale: 1, y: 0 }}
        exit={{ scale: 0.9, y: 20 }}
        transition={{ type: "spring", damping: 25, stiffness: 300 }}
        className="bg-white rounded-xl shadow-xl w-full max-w-md overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold">Configuração Inicial</h2>
            <Button variant="ghost" size="icon" onClick={onClose}>
              <X className="h-5 w-5" />
              <span className="sr-only">Fechar</span>
            </Button>
          </div>

          <div className="space-y-4">
            <div className="bg-blue-50 p-4 rounded-lg text-blue-800 text-sm mb-4">
              <p>
                Bem-vindo ao sistema de controle financeiro do comitê de formatura! Para começar, informe o capital
                inicial disponível.
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="initial-capital">Capital Inicial (R$)</Label>
              <div className="relative">
                <DollarSign className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 h-4 w-4" />
                <Input
                  id="initial-capital"
                  type="number"
                  placeholder="0.00"
                  value={value}
                  onChange={(e) => setValue(e.target.value)}
                  className="pl-10"
                  min="0"
                  step="0.01"
                />
              </div>
              <p className="text-xs text-gray-500">
                Este valor representa o dinheiro já disponível para o comitê no início do controle.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-gray-50 px-6 py-4 flex justify-end">
          <Button onClick={handleSave}>Salvar e Continuar</Button>
        </div>
      </motion.div>
    </motion.div>
  )
}

// src/components/InitialCapitalModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal-fade">
      <div
        v-if="isOpen"
        class="fixed inset-0 bg-black/50 flex items-center justify-center p-2 sm:p-4 z-50"
        @click="closeModal"
      >
        <div
          class="bg-white rounded-xl shadow-xl w-full max-w-sm sm:max-w-md overflow-hidden"
          @click.stop
        >
          <div class="p-4 sm:p-6">
            <div class="flex justify-between items-center mb-4">
              <h2 class="text-lg sm:text-xl font-bold">Boas-vindas ao Controle Financeiro</h2>
              <Button variant="ghost" size="icon" @click="closeModal">
                <X class="h-5 w-5" />
                <span class="sr-only">Fechar</span>
              </Button>
            </div>

            <div class="space-y-4">
              <p class="text-sm sm:text-base">Para começarmos a rastrear as finanças do comitê, precisamos do valor inicial do caixa.</p>

              <div class="space-y-2">
                <Label for="initial-amount">Valor inicial (R$)</Label>
                <div class="relative">
                  <DollarSign class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 h-4 w-4" />
                  <Input
                    id="initial-amount"
                    type="number"
                    v-model="initialAmount"
                    placeholder="0.00"
                    class="pl-10"
                    min="0"
                    step="0.01"
                  />
                </div>
              </div>

              <Alert v-if="error" variant="destructive">
                <AlertCircle class="h-4 w-4" />
                <AlertTitle>Erro</AlertTitle>
                <AlertDescription>{{ error }}</AlertDescription>
              </Alert>
            </div>
          </div>

          <div class="bg-gray-50 px-4 sm:px-6 py-3 sm:py-4 flex justify-end">
            <Button @click="saveInitialAmount" :disabled="loading">
              <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
              Confirmar e continuar
            </Button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue';
import { X, DollarSign, Loader2, AlertCircle } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { useCapitalStore } from '@/stores/capital';

export default defineComponent({
  name: 'InitialCapitalModal',
  components: {
    X, DollarSign, Loader2, AlertCircle,
    Button, Input, Label, Alert, AlertTitle, AlertDescription
  },
  emits: ['close'],
  setup(_, { emit }) {
    const isOpen = ref(false);
    const initialAmount = ref('');
    const loading = ref(false);
    const error = ref<string | null>(null);
    const capitalStore = useCapitalStore();

    // Verificar se o capital inicial já foi definido
    onMounted(async () => {
      try {
        const capitalStatus = await capitalStore.getCapital();

        // Só mostra o modal se o capital inicial não tiver sido definido
        if (!capitalStatus.initialSetted) {
          isOpen.value = true;
        }
      } catch (err) {
        console.error('Erro ao verificar status do capital:', err);
      }
    });

    const saveInitialAmount = async () => {
      if (!initialAmount.value || parseFloat(initialAmount.value) < 0) {
        error.value = 'Por favor, insira um valor válido.';
        return;
      }

      loading.value = true;
      error.value = null;

      try {
        await capitalStore.setInitialCapital(parseFloat(initialAmount.value));
        closeModal();
      } catch (err) {
        console.error('Erro ao salvar valor inicial:', err);
        error.value = 'Ocorreu um erro ao salvar o valor. Tente novamente.';
      } finally {
        loading.value = false;
      }
    };

    const closeModal = () => {
      isOpen.value = false;
      emit('close');
    };

    return {
      isOpen,
      initialAmount,
      loading,
      error,
      saveInitialAmount,
      closeModal
    };
  }
});
</script>

<style scoped>
.modal-fade-enter-active,
.modal-fade-leave-active {
  transition: opacity 0.3s;
}

.modal-fade-enter-from,
.modal-fade-leave-to {
  opacity: 0;
}
</style>
