// src/components/Dashboard.vue
<template>
  <Transition name="dashboard-fade" appear @before-enter="beforeEnter" @enter="enter">
    <!-- Container do Dashboard -->
    <div class="bg-background rounded-xl shadow-md overflow-hidden border-2">
      <!-- Parte de cima / header do card principal -->
      <div class="p-6 bg-gradient-to-r from-emerald-500 to-teal-600 dark:from-violet-600 dark:to-indigo-900 text-white">
        <h1 class="text-2xl font-bold mb-1">Comitê de Formatura - CEMIC 2025</h1>
        <p class="opacity-90">Controle de receitas e despesas</p>
      </div>

      <!-- Cards de visualização de dados principais -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 p-6">
        <!-- Card 1: capital atual -->
        <Card>
          <CardContent class="pt-1">
            <div class="flex items-center justify-between">
              <div>
                <p
                  class="text-sm bg-clip-text bg-gradient-to-r from-emerald-500 to-teal-600 dark:from-emerald-300 dark:to-teal-400 text-transparent mb-2 font-bold">
                  Capital Atual</p>
                <p class="text-2xl font-bold">R$ {{ capital.currentAmount?.toFixed(2) }}</p>
              </div>
              <div class="h-12 w-12 ml-5 rounded-full bg-emerald-100 flex items-center justify-center">
                <DollarSign class="h-6 w-6 text-emerald-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Card 2: total arrecadado -->
        <Card>
          <CardContent class="pt-1">
            <div class="flex items-center justify-between">
              <div>
                <p
                  class="text-sm bg-clip-text bg-gradient-to-r from-emerald-500 to-teal-600 dark:from-emerald-300 dark:to-teal-400 text-transparent mb-2 font-bold">
                  Total Arrecadado</p>
                <p class="text-2xl font-bold">R$ {{ capital.totalAmount?.toFixed(2) }}</p>
              </div>
              <div class="h-12 w-12 ml-5 rounded-full bg-emerald-100 flex items-center justify-center">
                <ArrowUp class="h-6 w-6 text-green-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Card 3: total gasto -->
        <Card>
          <CardContent class="pt-1">
            <div class="flex items-center justify-between">
              <div>
                <p
                  class="text-sm bg-clip-text bg-gradient-to-r from-rose-600 to-red-700 text-transparent dark:from-rose-300 dark:to-red-400 mb-2 font-bold">
                  Total gasto</p>
                <p class="text-2xl font-bold">R$ {{ totalExpenses.toFixed(2) }}</p>
              </div>
              <div class="h-12 w-12 ml-5 rounded-full bg-red-100 flex items-center justify-center">
                <ArrowDown class="h-6 w-6 text-red-600" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div class="px-6 pb-6">
        <Card>
          <CardContent class="pt-6">
            <div class="flex items-center mb-2">
              <Target class="h-5 w-5 text-purple-600 mr-2" />
              <h3 class="font-medium">Progresso para Meta</h3>
            </div>

            <div class="mb-2">
              <Progress :model-value="progressPercentage" class="h-2" />
            </div>

            <div class="flex justify-between text-sm">
              <div>
                <span class="text-gray-500">Meta:</span> R$ {{ meta.goalValue?.toFixed(2) }}
              </div>
              <div>
                <span class="text-gray-500">Falta:</span> R$ {{ remainingToGoal.toFixed(2) }}
              </div>
              <div>
                <span class="text-gray-500">Progresso:</span> {{ progressPercentage.toFixed(2) }}%
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </Transition>
</template>

<script lang="ts">
import { ArrowDown, ArrowUp, DollarSign, Target } from 'lucide-vue-next';
import { Card, CardContent } from './ui/card';
import { Progress } from './ui/progress';
import { defineComponent, Transition, PropType, computed } from 'vue';
import { useCapitalStore } from '@/stores/capital';
import Despesa from '@/types/Despesa';
import { useDespesaStore } from '@/stores/despesas';
import Meta from '@/types/Meta';
import { useMetaStore } from '@/stores/meta';
import { CapitalStatus } from '@/api/capitalService';

export default defineComponent({
  name: "Dashboard",
  props: {
    initialCapital: {
      type: Number,
      required: true
    },
    totalRaised: {
      type: Number,
      required: true
    },
    totalSpent: {
      type: Number,
      required: true
    },
    currentBalance: {
      type: Number,
      required: true
    },
    goal: {
      type: Number,
      required: true
    }
  },
  data() {
    return {
      capital: {
        currentAmount: 0,
        initialAmount: 0,
        totalAmount: 0,
        initialSetted: false
      } as CapitalStatus,
      despesas: [] as Despesa[],
      meta: {} as Meta,
      totalExpenses: 0 as number, // Renomeado para evitar conflito com props
      progressPercentage: 0 as number,
      remainingToGoal: 0 as number,
    }
  },
  methods: {
    beforeEnter(el: Element) {
      const htmlEl = el as HTMLElement;
      htmlEl.style.opacity = "0";
      htmlEl.style.transform = "translateY(-20px)";
    },
    enter(el: Element, done: () => void) {
      const htmlEl = el as HTMLElement;
      setTimeout(() => {
        htmlEl.style.transition = "all 0.5s ease";
        htmlEl.style.opacity = "1";
        htmlEl.style.transform = "translateY(0)";
      }, 0);

      el.addEventListener("transitionend", done);
    },
    getTotalSpent() {
      return this.despesas.reduce((accumulator: number, d: Despesa) => accumulator + d.totalCost, 0);
    },
    getProgressPercentage() {
      return (this.meta.currentValue / this.meta.goalValue) * 100;
    },
    getRemainingToGoal() {
      return this.meta.goalValue - this.meta.currentValue;
    }
  },
  setup(props) {
    // Renomear totalSpent prop para totalSpentValue para evitar conflito
    const totalSpentValue = computed(() => props.totalSpent);

    const formatCurrency = (value: number) => {
      return value.toFixed(2).replace('.', ',');
    };

    const progressPercentage = computed(() => {
      if (props.goal <= 0) return 0;

      const percentage = (props.currentBalance / props.goal) * 100;
      return Math.min(Math.round(percentage), 100);
    });

    return {
      formatCurrency,
      progressPercentage,
      totalSpentValue
    };
  },
  async created() {
    const capitalStore = useCapitalStore();
    const despesaStore = useDespesaStore();
    const metaStore = useMetaStore();

    try {
      const capitalStatus = await capitalStore.getCapitalStatus();
      if (capitalStatus) {
        this.capital = capitalStatus;
      }

      this.despesas = await despesaStore.getDespesas();
      this.meta = await metaStore.getMeta();
      this.totalExpenses = this.getTotalSpent(); // Usando o nome correto aqui
      this.progressPercentage = this.getProgressPercentage();
      this.remainingToGoal = this.getRemainingToGoal();
    } catch (error) {
      console.error("Erro ao carregar dados:", error);
    }
  },
  components: {
    Card,
    CardContent,
    Progress,
    ArrowDown,
    ArrowUp,
    DollarSign,
    Target,
    Transition
  },
});
</script>

// componentes-v0/components/dashboard.tsx
"use client"

import { ArrowUp, ArrowDown, DollarSign, Target } from "lucide-react"
import { motion } from "framer-motion"

import { Card, CardContent } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

interface DashboardProps {
  initialCapital: number
  totalRaised: number
  totalSpent: number
  currentBalance: number
  goal: number
}

export default function Dashboard({ initialCapital, totalRaised, totalSpent, currentBalance, goal }: DashboardProps) {
  // Calculate progress percentage
  const progressPercentage = goal > 0 ? Math.min(Math.round((currentBalance / goal) * 100), 100) : 0
  const remainingToGoal = Math.max(goal - currentBalance, 0)

  return (
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-white rounded-xl shadow-md overflow-hidden"
    >
      <div className="p-6 bg-gradient-to-r from-emerald-500 to-teal-600 text-white">
        <h1 className="text-2xl font-bold mb-1">Comitê de Formatura 2025</h1>
        <p className="opacity-90">Controle de receitas e despesas</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 p-6">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 mb-1">Capital Inicial</p>
                <p className="text-2xl font-bold">R$ {initialCapital.toFixed(2)}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-emerald-100 flex items-center justify-center">
                <DollarSign className="h-6 w-6 text-emerald-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 mb-1">Total Arrecadado</p>
                <p className="text-2xl font-bold">R$ {totalRaised.toFixed(2)}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-green-100 flex items-center justify-center">
                <ArrowUp className="h-6 w-6 text-green-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 mb-1">Total Gasto</p>
                <p className="text-2xl font-bold">R$ {totalSpent.toFixed(2)}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-red-100 flex items-center justify-center">
                <ArrowDown className="h-6 w-6 text-red-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 mb-1">Saldo Atual</p>
                <p className="text-2xl font-bold">R$ {currentBalance.toFixed(2)}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-blue-100 flex items-center justify-center">
                <DollarSign className="h-6 w-6 text-blue-600" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="px-6 pb-6">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center mb-2">
              <Target className="h-5 w-5 text-purple-600 mr-2" />
              <h3 className="font-medium">Progresso para Meta</h3>
            </div>

            <div className="mb-2">
              <Progress value={progressPercentage} className="h-2" />
            </div>

            <div className="flex justify-between text-sm">
              <div>
                <span className="text-gray-500">Meta:</span> R$ {goal.toFixed(2)}
              </div>
              <div>
                <span className="text-gray-500">Falta:</span> R$ {remainingToGoal.toFixed(2)}
              </div>
              <div>
                <span className="text-gray-500">Progresso:</span> {progressPercentage}%
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </motion.div>
  )
}
