// src/components/DayModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal-fade">
      <div
        v-if="isOpen"
        class="fixed inset-0 bg-black/50 flex items-center justify-center p-0 sm:p-4 z-50"
        @click="onClose"
      >
        <div
          class="bg-white rounded-t-xl sm:rounded-xl shadow-xl w-full h-[90vh] sm:h-auto sm:max-w-md
                 overflow-hidden max-h-[90vh] sm:max-h-[85vh] overflow-y-auto absolute bottom-0 sm:relative"
          :class="{ 'scale-100': isOpen, 'translate-y-0': isOpen }"
          style="transition: transform 0.3s ease, opacity 0.3s ease;"
          @click.stop
        >
          <!-- Puxador móvel no topo para UX de sheet em mobile -->
          <div class="w-12 h-1.5 bg-gray-300 rounded-full mx-auto mt-2 mb-1 sm:hidden"></div>

          <div class="p-4 sm:p-6">
            <div class="flex justify-between items-center mb-4">
              <h2 class="text-lg sm:text-xl font-bold">{{ formatDate(date, "EEEE, dd 'de' MMMM") }}</h2>
              <Button variant="ghost" size="icon" @click="onClose">
                <X class="h-5 w-5" />
                <span class="sr-only">Fechar</span>
              </Button>
            </div>

            <div class="flex items-center space-x-2 mb-4 sm:mb-6">
              <Switch id="trote-day" v-model="isTroteDay" />
              <Label for="trote-day">Dia de Trote</Label>
            </div>

            <Tabs default-value="items" class="space-y-4">
              <TabsList class="grid w-full grid-cols-2">
                <TabsTrigger value="items" class="text-sm">Itens</TabsTrigger>
                <TabsTrigger value="chart" class="text-sm">Gráfico</TabsTrigger>
              </TabsList>

              <TabsContent value="items" class="space-y-4 pt-2">
                <h3 class="font-medium text-gray-700">Itens Vendidos</h3>

                <div
                  v-for="item in items"
                  :key="item.id"
                  class="flex items-center justify-between py-2"
                  :class="{ 'hidden': item.isTroteItem && !isTroteDay }"
                >
                  <div class="flex items-center gap-2">
                    <component :is="item.icon" class="h-4 w-4" />
                    <div>
                      <span>{{ item.name }}</span>
                      <div class="text-xs text-gray-500">R$ {{ item.price.toFixed(2) }}</div>
                    </div>
                  </div>
                  <div class="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="icon"
                      class="h-10 w-10 sm:h-8 sm:w-8"
                      @click="handleDecrement(item.id)"
                      :disabled="item.count === 0"
                    >
                      <span>-</span>
                    </Button>
                    <span class="w-8 text-center">{{ item.count }}</span>
                    <Button variant="outline" size="icon" class="h-10 w-10 sm:h-8 sm:w-8" @click="handleIncrement(item.id)">
                      <span>+</span>
                    </Button>
                  </div>
                </div>

                <template v-if="customItems.length > 0">
                  <Separator class="my-4" />
                  <h3 class="font-medium text-gray-700">Outros Itens</h3>

                  <div
                    v-for="item in customItems"
                    :key="item.id"
                    class="flex items-center justify-between py-2"
                  >
                    <div class="flex items-center gap-2">
                      <component :is="item.icon" class="h-4 w-4" />
                      <div>
                        <span>{{ item.name }}</span>
                        <div class="text-xs text-gray-500">R$ {{ item.price.toFixed(2) }}</div>
                      </div>
                    </div>
                    <div class="flex items-center gap-2">
                      <Button
                        variant="outline"
                        size="icon"
                        class="h-10 w-10 sm:h-8 sm:w-8"
                        @click="handleDecrementCustom(item.id)"
                        :disabled="item.count === 0"
                      >
                        <span>-</span>
                      </Button>
                      <span class="w-8 text-center">{{ item.count }}</span>
                      <Button
                        variant="outline"
                        size="icon"
                        class="h-10 w-10 sm:h-8 sm:w-8"
                        @click="handleIncrementCustom(item.id)"
                      >
                        <span>+</span>
                      </Button>
                    </div>
                  </div>
                </template>

                <Separator class="my-4" />

                <div class="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  <div class="sm:col-span-2">
                    <Input
                      placeholder="Adicionar outro item..."
                      v-model="customItemName"
                    />
                  </div>
                  <div>
                    <Input
                      placeholder="Preço"
                      inputmode="decimal"
                      v-model="customItemPrice"
                    />
                  </div>
                </div>

                <Button
                  @click="handleAddCustomItem"
                  :disabled="!customItemName.trim() || !(Number.parseFloat(customItemPrice) > 0)"
                  class="w-full py-6 sm:py-2"
                >
                  <Plus class="h-4 w-4 mr-1" />
                  <span>Adicionar Item</span>
                </Button>
              </TabsContent>

              <TabsContent value="chart">
                <div class="space-y-4">
                  <div class="flex justify-between items-center">
                    <h3 class="font-medium text-gray-700">Resumo de Vendas</h3>
                    <PieChart class="h-5 w-5 text-gray-500" />
                  </div>

                  <div class="h-[35vh] sm:h-[40vh] mx-auto">
                    <div v-if="totalSales > 0">
                      <BarChart
                        index="id"
                        :data="chartData"
                        :categories="['value']"
                        :y-formatter="(tick) => `R$ ${typeof tick === 'number' ? tick.toFixed(2) : ''}`"
                        :colors="['rgba(75, 192, 192, 0.6)']"
                        :rounded-corners="4"
                      />
                    </div>
                    <div v-else class="h-full flex items-center justify-center text-center">
                      <div class="text-gray-500">
                        <PieChart class="h-12 w-12 mx-auto mb-2 opacity-20" />
                        <p>Adicione itens para visualizar o gráfico</p>
                      </div>
                    </div>
                  </div>

                  <div class="bg-gray-50 p-4 rounded-lg">
                    <div class="flex justify-between mb-2">
                      <span class="text-gray-600">Total de Vendas:</span>
                      <span class="font-bold">R$ {{ formatCurrency(totalSales) }}</span>
                    </div>
                    <div class="flex justify-between">
                      <span class="text-gray-600">Itens Diferentes:</span>
                      <span class="font-bold">
                        {{ [...items, ...customItems].filter(item => item.count > 0).length }}
                      </span>
                    </div>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>

          <!-- Botão de salvar fixo na parte inferior em mobile -->
          <div class="bg-gray-50 px-6 py-4 sm:flex justify-end sticky bottom-0 left-0 right-0 shadow-md sm:shadow-none">
            <div class="grid grid-cols-2 sm:flex sm:grid-cols-none gap-2">
              <Button variant="outline" @click="onClose" class="w-full sm:w-auto">
                Cancelar
              </Button>
              <Button
                @click="handleSave"
                :disabled="totalSales <= 0"
                class="w-full sm:w-auto"
              >
                Salvar
              </Button>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script lang="ts">
import { defineComponent, PropType, ref, computed, watch } from 'vue';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { X, Coffee, Droplet, IceCream, Ticket, Heart, Mail, Plus, PieChart } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { BarChart } from '@/components/ui/chart-bar';
import vendaService from '@/api/vendaService';
import { useTroteStore } from '@/stores/trote';
import { storeToRefs } from 'pinia';

interface SaleItem {
  id: string;
  name: string;
  icon: any;
  count: number;
  price: number;
  isTroteItem?: boolean;
}

// Mapeamento de IDs para ItemType do backend
const ITEM_TYPE_MAPPING = {
  'soda-cup': 'REFRI_COPO',
  'soda-bottle': 'REFRI_GARRAFA',
  'popsicle': 'PICOLE',
  'bingo': 'CARTELA_BINGO',
  'love-chain': 'OUTROS',
  'elegant-mail': 'CORREIO_ELEGANTE'
};

// Product prices
const PRICES = {
  "soda-cup": 2.5,
  "soda-bottle": 15,
  "popsicle": 4,
  "bingo": 2.5,
  "love-chain": 2.0,
  "elegant-mail": 1.5,
};

export default defineComponent({
  name: 'DayModal',
  components: {
    X, Coffee, Droplet, IceCream, Ticket, Heart, Mail, Plus, PieChart,
    Button, Input, Label, Switch, Separator, Tabs, TabsContent, TabsList, TabsTrigger,
    BarChart,
  },
  props: {
    date: {
      type: Object as PropType<Date>,
      required: true,
    },
    isOpen: {
      type: Boolean,
      default: false
    }
  },
  emits: ['update:is-open', 'save'],
  setup(props, { emit }) {
    const troteStore = useTroteStore();
    const isTroteDay = ref(false);
    const customItemName = ref('');
    const customItemPrice = ref('');
    const loading = ref(false);

    // Inicializar isTroteDay com valor do store
    watch(() => props.date, () => {
      if (props.date) {
        const day = props.date.getDate().toString().padStart(2, '0');
        const month = (props.date.getMonth() + 1).toString().padStart(2, '0');
        const year = props.date.getFullYear();
        const dateStr = `${day}-${month}-${year}`;

        isTroteDay.value = troteStore.isTroteDay(dateStr);
      }
    }, { immediate: true });

    // Initial sales items
    const items = ref<SaleItem[]>([
      {
        id: "soda-cup",
        name: "Refri (copo)",
        icon: Droplet,
        count: 0,
        price: PRICES["soda-cup"],
      },
      {
        id: "soda-bottle",
        name: "Refri (garrafa)",
        icon: Coffee,
        count: 0,
        price: PRICES["soda-bottle"],
      },
      {
        id: "popsicle",
        name: "Picolé",
        icon: IceCream,
        count: 0,
        price: PRICES["popsicle"]
      },
      {
        id: "bingo",
        name: "Cartela de Bingo",
        icon: Ticket,
        count: 0,
        price: PRICES["bingo"],
        isTroteItem: true,
      },
      {
        id: "love-chain",
        name: "Cadeia do Amor",
        icon: Heart,
        count: 0,
        price: PRICES["love-chain"],
        isTroteItem: true,
      },
      {
        id: "elegant-mail",
        name: "Correio Elegante",
        icon: Mail,
        count: 0,
        price: PRICES["elegant-mail"],
        isTroteItem: true,
      }
    ]);

    const customItems = ref<SaleItem[]>([]);

    // Calculate total sales
    const totalSales = computed(() => {
      return [...items.value, ...customItems.value].reduce((total, item) => {
        return total + item.count * item.price;
      }, 0);
    });

    // Prepare chart data for shadcn-vue BarChart
    const chartData = computed(() => {
      return [...items.value, ...customItems.value]
        .filter(item => item.count > 0)
        .map(item => ({
          id: item.name,
          name: item.name,
          value: item.count * item.price
        }));
    });

    const formatDate = (date: Date, formatStr: string): string => {
      return format(date, formatStr, { locale: ptBR });
    };

    const formatCurrency = (value: number): string => {
      return value.toFixed(2).replace('.', ',');
    };

    const formatDateStr = (date: Date): string => {
      const day = date.getDate().toString().padStart(2, '0');
      const month = (date.getMonth() + 1).toString().padStart(2, '0');
      const year = date.getFullYear();
      return `${day}-${month}-${year}`;
    };

    const formatDateForBackend = (date: Date): string => {
      const day = date.getDate().toString().padStart(2, '0');
      const month = (date.getMonth() + 1).toString().padStart(2, '0');
      const year = date.getFullYear();
      return `${day}/${month}/${year}`;
    };

    const handleIncrement = (id: string) => {
      items.value = items.value.map(item => {
        if (item.id === id) {
          return { ...item, count: item.count + 1 };
        }
        return item;
      });
    };

    const handleDecrement = (id: string) => {
      items.value = items.value.map(item => {
        if (item.id === id && item.count > 0) {
          return { ...item, count: item.count - 1 };
        }
        return item;
      });
    };

    const handleIncrementCustom = (id: string) => {
      customItems.value = customItems.value.map(item => {
        if (item.id === id) {
          return { ...item, count: item.count + 1 };
        }
        return item;
      });
    };

    const handleDecrementCustom = (id: string) => {
      customItems.value = customItems.value.map(item => {
        if (item.id === id && item.count > 0) {
          return { ...item, count: item.count - 1 };
        }
        return item;
      });
    };

    const handleAddCustomItem = () => {
      if (customItemName.value.trim() && Number.parseFloat(customItemPrice.value) > 0) {
        const newItem: SaleItem = {
          id: `custom-${Date.now()}`,
          name: customItemName.value,
          icon: Plus,
          count: 0,
          price: Number.parseFloat(customItemPrice.value),
        };
        customItems.value.push(newItem);
        customItemName.value = '';
        customItemPrice.value = '';
      }
    };

    const handleSave = async () => {
      loading.value = true;

      try {
        // Se for dia de trote, salva no store global
        if (isTroteDay.value) {
          const dateStr = formatDateStr(props.date);
          troteStore.setTroteDay(dateStr);
        }

        // Preparar e enviar todos os itens com quantidade > 0
        const vendaPromises = [];
        const savedItems = [];

        // Processar itens padrão
        for (const item of items.value) {
          if (item.count > 0) {
            const venda = {
              date: formatDateForBackend(props.date),
              itemType: ITEM_TYPE_MAPPING[item.id] || 'OUTROS',
              quantity: item.count,
              unitPrice: item.price,
              totalPrice: item.count * item.price,
              notes: isTroteDay.value ? 'Dia de Trote' : ''
            };

            try {
              const savedVenda = await vendaService.addVenda(venda);
              savedItems.push({
                id: item.id,
                name: item.name,
                count: item.count,
                price: item.price,
                total: item.count * item.price
              });

              vendaPromises.push(Promise.resolve(savedVenda));
            } catch (error) {
              console.error(`Erro ao salvar item ${item.id}:`, error);
              vendaPromises.push(Promise.reject(error));
            }
          }
        }

        // Processar itens customizados
        for (const item of customItems.value) {
          if (item.count > 0) {
            const venda = {
              date: formatDateForBackend(props.date),
              itemType: 'OUTROS',
              quantity: item.count,
              unitPrice: item.price,
              totalPrice: item.count * item.price,
              notes: `${item.name}${isTroteDay.value ? ' - Dia de Trote' : ''}`
            };

            try {
              const savedVenda = await vendaService.addVenda(venda);
              savedItems.push({
                id: item.id,
                name: item.name,
                count: item.count,
                price: item.price,
                total: item.count * item.price
              });

              vendaPromises.push(Promise.resolve(savedVenda));
            } catch (error) {
              console.error(`Erro ao salvar item personalizado ${item.id}:`, error);
              vendaPromises.push(Promise.reject(error));
            }
          }
        }

        await Promise.all(vendaPromises);

        // Criar o objeto de venda completo para emitir
        const saleData = {
          date: formatDateForBackend(props.date),
          isTroteDay: isTroteDay.value,
          items: savedItems,
          totalAmount: totalSales.value // Certifique-se de que este valor é acessível
        };

        emit('save', saleData);
        emit('update:is-open', false);
      } catch (error) {
        console.error('Erro ao salvar vendas:', error);
      } finally {
        loading.value = false;
      }
    };

    const onClose = () => {
      emit('update:is-open', false);
    };

    return {
      isTroteDay,
      customItemName,
      customItemPrice,
      items,
      customItems,
      totalSales,
      chartData,
      loading,
      formatDate,
      formatCurrency,
      handleIncrement,
      handleDecrement,
      handleIncrementCustom,
      handleDecrementCustom,
      handleAddCustomItem,
      handleSave,
      onClose
    };
  }
});
</script>

<style scoped>
.modal-fade-enter-active,
.modal-fade-leave-active {
  transition: opacity 0.3s, transform 0.3s;
}

.modal-fade-enter-from,
.modal-fade-leave-to {
  opacity: 0;
}

@media (max-width: 640px) {
  .modal-fade-enter-from .bg-white,
  .modal-fade-leave-to .bg-white {
    transform: translateY(100%);
  }
}

@media (min-width: 641px) {
  .modal-fade-enter-from .bg-white,
  .modal-fade-leave-to .bg-white {
    transform: scale(0.9) translateY(20px);
  }
}

/* Melhor suporte a gestos de arrasto para mobile com sheet */
@media (max-width: 640px) {
  .modal-fade-enter-active .bg-white,
  .modal-fade-leave-active .bg-white {
    transition: transform 0.3s cubic-bezier(0.16, 1, 0.3, 1);
  }
}
</style>

// componentes-v0/components/day-modal.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { format } from "date-fns"
import { ptBR } from "date-fns/locale"
import { motion } from "framer-motion"
import { X, Coffee, Droplet, IceCream, Ticket, Heart, Mail, Plus, PieChart } from "lucide-react"
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement, Title } from "chart.js"
import { Bar } from "react-chartjs-2"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Separator } from "@/components/ui/separator"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { cn } from "@/lib/utils"

// Register ChartJS components
ChartJS.register(ArcElement, CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend)

interface DayModalProps {
  date: Date
  onClose: () => void
  onSave: (sale: any) => void
}

interface SaleItem {
  id: string
  name: string
  icon: React.ReactNode
  count: number
  price: number
  isTroteItem?: boolean
}

// Product prices
const PRICES = {
  "soda-cup": 3.5,
  "soda-bottle": 5.0,
  popsicle: 2.5,
  bingo: 10.0,
  "love-chain": 2.0,
  "elegant-mail": 1.5,
}

export default function DayModal({ date, onClose, onSave }: DayModalProps) {
  const [isTroteDay, setIsTroteDay] = useState(false)
  const [customItemName, setCustomItemName] = useState("")
  const [customItemPrice, setCustomItemPrice] = useState("")

  // Initial sales items
  const [items, setItems] = useState<SaleItem[]>([
    {
      id: "soda-cup",
      name: "Refri (copo)",
      icon: <Droplet className="h-4 w-4" />,
      count: 0,
      price: PRICES["soda-cup"],
    },
    {
      id: "soda-bottle",
      name: "Refri (garrafa)",
      icon: <Coffee className="h-4 w-4" />,
      count: 0,
      price: PRICES["soda-bottle"],
    },
    { id: "popsicle", name: "Picolé", icon: <IceCream className="h-4 w-4" />, count: 0, price: PRICES["popsicle"] },
    {
      id: "bingo",
      name: "Cartela de Bingo",
      icon: <Ticket className="h-4 w-4" />,
      count: 0,
      price: PRICES["bingo"],
      isTroteItem: true,
    },
    {
      id: "love-chain",
      name: "Cadeia do Amor",
      icon: <Heart className="h-4 w-4" />,
      count: 0,
      price: PRICES["love-chain"],
      isTroteItem: true,
    },
    {
      id: "elegant-mail",
      name: "Correio Elegante",
      icon: <Mail className="h-4 w-4" />,
      count: 0,
      price: PRICES["elegant-mail"],
      isTroteItem: true,
    },
  ])

  const [customItems, setCustomItems] = useState<SaleItem[]>([])

  // Calculate total sales
  const totalSales = [...items, ...customItems].reduce((total, item) => {
    return total + item.count * item.price
  }, 0)

  // Prepare chart data
  const chartData = {
    labels: [...items, ...customItems].filter((item) => item.count > 0).map((item) => item.name),
    datasets: [
      {
        label: "Valor (R$)",
        data: [...items, ...customItems].filter((item) => item.count > 0).map((item) => item.count * item.price),
        backgroundColor: "rgba(75, 192, 192, 0.6)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
    ],
  }

  // Chart options
  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    scales: {
      y: {
        beginAtZero: true,
        ticks: {
          callback: (value: any) => `R$ ${value}`,
        },
      },
      x: {
        ticks: {
          maxRotation: 45,
          minRotation: 45,
          autoSkip: true,
          maxTicksLimit: 8,
        },
      },
    },
    plugins: {
      legend: {
        display: false,
      },
    },
  }

  const handleIncrement = (id: string) => {
    setItems((prev) => prev.map((item) => (item.id === id ? { ...item, count: item.count + 1 } : item)))
  }

  const handleDecrement = (id: string) => {
    setItems((prev) =>
      prev.map((item) => (item.id === id && item.count > 0 ? { ...item, count: item.count - 1 } : item)),
    )
  }

  const handleIncrementCustom = (id: string) => {
    setCustomItems((prev) => prev.map((item) => (item.id === id ? { ...item, count: item.count + 1 } : item)))
  }

  const handleDecrementCustom = (id: string) => {
    setCustomItems((prev) =>
      prev.map((item) => (item.id === id && item.count > 0 ? { ...item, count: item.count - 1 } : item)),
    )
  }

  const handleAddCustomItem = () => {
    if (customItemName.trim() && Number.parseFloat(customItemPrice) > 0) {
      const newItem: SaleItem = {
        id: `custom-${Date.now()}`,
        name: customItemName,
        icon: <Plus className="h-4 w-4" />,
        count: 0,
        price: Number.parseFloat(customItemPrice),
      }
      setCustomItems((prev) => [...prev, newItem])
      setCustomItemName("")
      setCustomItemPrice("")
    }
  }

  const handleSave = () => {
    // Prepare sales data
    const salesData = {
      date: format(date, "yyyy-MM-dd"),
      isTroteDay,
      items: [...items, ...customItems]
        .filter((item) => item.count > 0)
        .map((item) => ({
          id: item.id,
          name: item.name,
          count: item.count,
          price: item.price,
          total: item.count * item.price,
        })),
      totalAmount: totalSales,
    }

    onSave(salesData)
    onClose()
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, y: 20 }}
        animate={{ scale: 1, y: 0 }}
        exit={{ scale: 0.9, y: 20 }}
        transition={{ type: "spring", damping: 25, stiffness: 300 }}
        className="bg-white rounded-xl shadow-xl w-full max-w-md overflow-hidden max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold">{format(date, "EEEE, dd 'de' MMMM", { locale: ptBR })}</h2>
            <Button variant="ghost" size="icon" onClick={onClose}>
              <X className="h-5 w-5" />
              <span className="sr-only">Fechar</span>
            </Button>
          </div>

          <div className="flex items-center space-x-2 mb-6">
            <Switch id="trote-day" checked={isTroteDay} onCheckedChange={setIsTroteDay} />
            <Label htmlFor="trote-day">Dia de Trote</Label>
          </div>

          <Tabs defaultValue="items">
            <TabsList className="grid w-full grid-cols-2 mb-4">
              <TabsTrigger value="items">Itens</TabsTrigger>
              <TabsTrigger value="chart">Gráfico</TabsTrigger>
            </TabsList>

            <TabsContent value="items" className="space-y-4">
              <h3 className="font-medium text-gray-700">Itens Vendidos</h3>

              {items.map((item) => (
                <div
                  key={item.id}
                  className={cn("flex items-center justify-between py-2", item.isTroteItem && !isTroteDay && "hidden")}
                >
                  <div className="flex items-center gap-2">
                    {item.icon}
                    <div>
                      <span>{item.name}</span>
                      <div className="text-xs text-gray-500">R$ {item.price.toFixed(2)}</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="icon"
                      className="h-8 w-8"
                      onClick={() => handleDecrement(item.id)}
                      disabled={item.count === 0}
                    >
                      <span>-</span>
                    </Button>
                    <span className="w-8 text-center">{item.count}</span>
                    <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => handleIncrement(item.id)}>
                      <span>+</span>
                    </Button>
                  </div>
                </div>
              ))}

              {customItems.length > 0 && (
                <>
                  <Separator className="my-4" />
                  <h3 className="font-medium text-gray-700">Outros Itens</h3>

                  {customItems.map((item) => (
                    <div key={item.id} className="flex items-center justify-between py-2">
                      <div className="flex items-center gap-2">
                        {item.icon}
                        <div>
                          <span>{item.name}</span>
                          <div className="text-xs text-gray-500">R$ {item.price.toFixed(2)}</div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button
                          variant="outline"
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => handleDecrementCustom(item.id)}
                          disabled={item.count === 0}
                        >
                          <span>-</span>
                        </Button>
                        <span className="w-8 text-center">{item.count}</span>
                        <Button
                          variant="outline"
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => handleIncrementCustom(item.id)}
                        >
                          <span>+</span>
                        </Button>
                      </div>
                    </div>
                  ))}
                </>
              )}

              <Separator className="my-4" />

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <div className="sm:col-span-2">
                  <Input
                    placeholder="Adicionar outro item..."
                    value={customItemName}
                    onChange={(e) => setCustomItemName(e.target.value)}
                  />
                </div>
                <div>
                  <Input
                    placeholder="Preço"
                    type="number"
                    min="0"
                    step="0.01"
                    value={customItemPrice}
                    onChange={(e) => setCustomItemPrice(e.target.value)}
                  />
                </div>
              </div>

              <Button
                onClick={handleAddCustomItem}
                disabled={!customItemName.trim() || !(Number.parseFloat(customItemPrice) > 0)}
                className="w-full"
              >
                <Plus className="h-4 w-4 mr-1" />
                <span>Adicionar Item</span>
              </Button>
            </TabsContent>

            <TabsContent value="chart">
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <h3 className="font-medium text-gray-700">Resumo de Vendas</h3>
                  <PieChart className="h-5 w-5 text-gray-500" />
                </div>

                <div className="h-[40vh] max-h-[300px] mx-auto">
                  {totalSales > 0 ? (
                    <Bar data={chartData} options={chartOptions} />
                  ) : (
                    <div className="h-full flex items-center justify-center text-center">
                      <div className="text-gray-500">
                        <PieChart className="h-12 w-12 mx-auto mb-2 opacity-20" />
                        <p>Adicione itens para visualizar o gráfico</p>
                      </div>
                    </div>
                  )}
                </div>

                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="flex justify-between mb-2">
                    <span className="text-gray-600">Total de Vendas:</span>
                    <span className="font-bold">R$ {totalSales.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Itens Diferentes:</span>
                    <span className="font-bold">
                      {[...items, ...customItems].filter((item) => item.count > 0).length}
                    </span>
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>

        <div className="bg-gray-50 px-6 py-4 flex justify-end">
          <Button variant="outline" className="mr-2" onClick={onClose}>
            Cancelar
          </Button>
          <Button onClick={handleSave} disabled={totalSales <= 0}>
            Salvar
          </Button>
        </div>
      </motion.div>
    </motion.div>
  )
}
